Updates python versions to the more recent ones
infOpen/docker-pyenv-tox pull request #1
Opened 2018-12-20 14:44 UTC by ndclt

* 2.7.14 -> 2.7.15
* 3.4.7 -> 3.4.9
* 3.5.4 -> 3.5.6
* 3.6.3 -> 3.6.7
* append 3.7.1

2018-12-20 22:37 UTC, achaussier requested changes
Thanks for these updates, just fix the Dockerfile indent and I'll merge them

2018-12-20 22:37 UTC, achaussier commented on Dockerfile
> +    RUN git clone --depth 1 --branch v1.2.8 https://github.com/pyenv/pyenv.git ~/.pyenv && \
```suggestion
RUN git clone --depth 1 --branch v1.2.8 https://github.com/pyenv/pyenv.git ~/.pyenv && \
```

2018-12-21 07:23 UTC, ndclt commented on Dockerfile
> +    RUN git clone --depth 1 --branch v1.2.8 https://github.com/pyenv/pyenv.git ~/.pyenv && \
Done in be8588766e351efadee0bf8b1ca3cbd16fb3fa45.

2019-01-02 08:17 UTC, achaussier approved these changes

2019-01-02 08:17 UTC, merged